export enum Title {
    PRODUCT = 'PRODUCT',
    DESCRIPTION = 'DESCRIPTION',
    ADDED = 'ADDED',
    PRICE = 'PRICE',
    QUANTITY = 'QUANTITY',
    STATUS = 'STATUS',
    CATEGORY = 'CATEGORY',
    PRICE_HISTORY = 'PRICE HISTORY',
    PHOTOS = 'PHOTOS',
    ACTION = 'ACTION',
}
